import os
import re

BASE_DIR = os.path.dirname(os.path.dirname(__file__))  # backend/
MODELS_DIR = os.path.join(BASE_DIR, "app", "models")
INIT_FILE = os.path.join(MODELS_DIR, "__init__.py")

print(f"🔍 Génération automatique de {INIT_FILE}")

# Lister tous les fichiers Python sauf __init__.py et fichiers temporaires
model_files = [
    f for f in os.listdir(MODELS_DIR)
    if f.endswith(".py") and not f.startswith("__") and not f.startswith("_")
]

imports = []
all_models = []

for file in sorted(model_files):
    class_name = os.path.splitext(file)[0].capitalize()
    # essaye de détecter le vrai nom de la classe dans le fichier
    with open(os.path.join(MODELS_DIR, file), "r", encoding="utf-8") as f:
        content = f.read()
        match = re.search(r"class\s+(\w+)\(Base\):", content)
        if match:
            class_name = match.group(1)
    imports.append(f"from .{os.path.splitext(file)[0]} import {class_name}")
    all_models.append(f'"{class_name}"')

with open(INIT_FILE, "w", encoding="utf-8") as f:
    f.write("# Auto-generated by update_init_models.py\n")
    f.write("\n".join(imports))
    f.write("\n\n__all__ = [\n    " + ",\n    ".join(all_models) + "\n]\n")

print(f"✅ __init__.py mis à jour avec {len(all_models)} modèles : {', '.join(all_models)}")
